export const ProyectsInfoConstant = [    
    {
        Name: "PJ Line Gestion",
        Description: "Site of Judiciary of Costa Rice, wheren I've worked and some modules",        
        Stack: "Angular - .Net - Rest API - SqlServer",        
        Link: "https://pjenlinea.poder-judicial.go.cr/GestionEnLinea/inicio#googtrans(es%7Ces)",        
        ImageRoute: "https://i.imgur.com/CQfi6x9.png",        
    },
    {
        Name: "ANE",
        Description: "Free service that facilitates contact between job seekers and companies that require human talent",        
        Stack: ".Net Framework (C#), .Net MVC, Sql Server, Jquery",        
        Link: "https://www.ane.cr/",
        ImageRoute: "https://i.imgur.com/I1df0GQ.png",        
    },
    {
        Name: "EASY Conta",
        Description: "Product of my current Company, with focus on business accounting",        
        Stack: "Webforms, .Net Framwork, Sql Server, Jquery",        
        Link: "https://ebs-sys.com/sacristia",
        ImageRoute: "https://i.imgur.com/haR6ENy.png",        
    },    
    {
        Name: "DGAC",
        Description: "Invoice DGAC System of Costa Rica Civil Aviation",        
        Stack: ".Net 5, .Net MVC, Sql Server, Jquery",        
        Link: "https://cetacfacturacion.dgac.go.cr/",
        ImageRoute: "https://i.imgur.com/UzgZipM.png",        
    },    
    {
        Name: "My portfolio",
        Description: "Static page to share my experience.",        
        Stack: "React - Vite - Styled Component - Router",        
        Link: "",
        ImageRoute: "https://i.imgur.com/pOEJdRl.png",        
    },                
    {
        Name: "Go Rental",
        Description: "Informative and sales monitoring site.",        
        Stack: ".Net 6 - Entity Framework - JS",        
        Link: "https://www.gorentalcr.com/",
        ImageRoute: "https://i.imgur.com/0BpI9di.png",        
    },            
    {
        Name: "Patient Manager",
        Description: "I built it in my free time to learn more about the framework.",        
        Stack: "React - VITE - Tailwind - LocalStorage",        
        Link: "https://flamboyant-northcutt-b84f1d.netlify.app/",
        ImageRoute: "https://i.imgur.com/GJtYmnt.png",        
    },            
    {
        Name: "Budget Controller",
        Description: "Same, I built it in my free time to learn more about the framework.",        
        Stack: "Create React App - Bootstrap - LocalStorage",        
        Link: "https://jovial-colden-b4dd8f.netlify.app/",
        ImageRoute: "https://i.imgur.com/oc1wPkp.png",        
    },            
    // {
    //     Name: "Angular Crud",
    //     Description: "Simple angular CRUD.",        
    //     Stack: "Angular - .Net 6 - Tailwind - Routing",        
    //     Link: "https://github.com/fomega2/angular_first_crud",
    //     ImageRoute: "https://i.imgur.com/EDNMvYU.jpg",        
    // },            
    {
        Name: "Car Quoter",
        Description: "Simulation of Car Quotes.",        
        Stack: "Create React App - StyledComponents",        
        Link: "https://flamboyant-noyce-96c674.netlify.app/",
        ImageRoute: "https://i.imgur.com/LFIWwsq.png",        
    },            
    {
        Name: "Image Search",
        Description: "Simple image search.",        
        Stack: "React - Vite - Tailwind",        
        Link: "https://lovely-kheer-2e20b4.netlify.app/",
        ImageRoute: "https://i.imgur.com/9QEpeWG.png",        
    },                
    {
        Name: "HS WebSite",
        Description: "Informative and route manager site.",        
        Stack: ".Net 6 - Entity Framework - JS",        
        Link: "https://i.imgur.com/XbmboUx.png",
        ImageRoute: "https://i.imgur.com/XbmboUx.png",        
    }            
];